Makefile, bin/generate-templates.js, mkdocs.yml
=> feat: autogenerate templates text

.gitmodules, bin/generate-presets.js, mkdocs.yml
=> fix: presets docs

bin/generate-modules.js
* generating datasource index
* some small fixes
closes #21
=> docs: generate datasource index

README.md
- Fix wording
We're not referring to multiple repositories here, we just want them to open a PR at the main Renovate bot repo.
=> chore: fix wording

.github/contributing.md, README.md
- Create `contributing.md` (copy/paste from Renovate bot repo)
- Strip out parts of `contributing.md` that are not relevant to this repo.
- Create new section in `README.md` that points to this guide
I think it's nice to explain how to contribute to the repo.
=> chore: create contributing.md

src/index.md
- Reduce capitalization in headings
- Capitalize proper noun Markdown
- Simplify sentence
Small improvements to the index page.
=> docs: improve index page

bin/generate-modules.js
We recently add Datasource classes, which the docs currently doesn't repect.
So this will fix it
https://docs.renovatebot.com/modules/datasource/
=> fix: update datasources api

.prettierrc.json, bin/generate-config.js, bin/generate-modules.js, bin/generate-presets.js, bin/generate-templates.js, bin/get-docs.sh, package.json
=> feat: use esmodules

bin/generate-modules.js, bin/get-docs.sh
depends on https://github.com/renovatebot/renovate/pull/11423 for updating platform index page
=> feat: publish platform detail pages

bin/generate-modules.js
=> fix: wrong link title

src/index.md
- Update links so they point to their final location for speed
These links use a `www.` domain, but the links do not have `www.` in them.
Updating the links so we end up in the final location, without getting a redirect.
=> docs: update links on index page

mkdocs.yml
- Add replacement presets to sidebar
Closes #92.
First confirm file and folder are present on `main` (folder called `presets-replacements` should be there).
Marking this PR as draft until I can actually verify this works as intended.
=> docs: add replacement presets to sidebar

.github/local-development.md, .gitpod.yml
- Create Gitpod config
- Document how to use Gitpod in the development documentation
Closes #95.
=> chore: create Gitpod config

mkdocs.yml
- preparation for branch renaming
=> ci: publish to gh-pages branch

.github/workflows/publish-docs.yml
=> chore: disable gh-pages

.github/local-development.md
- Update base branch from `build` to `main`
We now use the `main` branch as the target for incoming pull requests, so the docs need to be updated.
=> docs(local-development) update base branch

.github/pull_request_template.md
- Update URL in PR template
We now use the `main` branch as the target for incoming PRs.
=> chore: update URL in PR template

src/index.md
- Simplify text
I think this is easier to read and understand, and gets to the point quicker.
This PR does not close any existing issue.
=> docs(index): simplify text

src/index.md
- Fix whitespace error 
Missed this when creating PR #115, sorry about that! 🙈
=> chore: fix whitespace

.github/contributing.md
- Fix typo in word `requirement` which should be `requirements`
- Expand abbreviation `ASAP` -> as soon as possible
- Update URL to `local-development.md` file
Small fixes to the document, not closing any issue with this PR.
=> docs(contributing): fix typo, expand abbreviation, update url

.github/workflows/publish-docs.yml, .husky/pre-commit, .prettierignore, .prettierrc.json, Makefile, package.json, src/assets/js/fx.js, yarn.lock
- Install Prettier and Husky as development dependencies
- Run Prettier on build step in GitHub Actions CI
- Before commit Husky runs `prettier` to check for style errors
- Add check to make sure you're not committing to `main` by accident (copy/pasted from `renovatebot/renovate`)
- Run `shellcheck` on the Husky precommit file
Closes #42, re-try of PR #104.
=> chore: setup Prettier and Husky precommit

.husky/pre-commit, .lintstagedrc.json, package.json, yarn.lock
=> chore: add lint-staged

mkdocs.yml
- Add Security and Permissions page to sidebar
Closes #141.
=> chore: add security and permissions to sidebar

Makefile, bin/build-docs.sh
- remove simple bash build wrapper
=> build: remove simply build wrapper

.github/workflows/publish-docs.yml
=> ci: use node v16

src/index.md
- Old link redirects to this new link
Speed up browsing by avoiding a redirect.
=> docs(index): update link to Mend homepage

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/refactor.yml, .github/contributing.md, README.md, SECURITY.md, src/security.txt
- Find and replace `renovate-disclosure@whitesourcesoftware.com` into `renovate-disclosure@mend.io`
Follow up after PR:
- https://github.com/renovatebot/renovate/pull/16797
=> docs: update security email

Makefile
=> build: fix deploy command

.gitignore
=> chore: ignore .venv

src/index.md
Added a link to our tutorial in the home page of the documents.
=> Update index.md to include link to tutorial

mkdocs.yml
- Add the new User Stories section to our sidebar
Closes #195.
=> chore: add user stories to sidebar

mkdocs.yml
- Enable image captions [^captions]
- Enable image lazy-loading [^lazy-loading]
Closes #211.
1. Run `make`
1. Copy-paste the markdown into the `docs/usage/swissquote` directory
1. Run `make serve`
1. Open the site preview, and go to the Swissquote article.
```markdown
> This article was originally published on [Medium](https://medium.com/swissquote-engineering/how-swissquote-is-keeping-software-dependencies-up-to-date-with-renovate-6246e8b20437) by [Stéphane Goetz](https://onigoetz.ch/), Principal Software Engineer at [Swissquote Bank](https://github.com/swissquote/)
Swissquote has more than 1000 distinct applications running in production.
They come in many different flavors including services, daemons, and webapps, and their age can be counted from days to more than a decade.
While …
```
=> chore: enable image captions and lazy loading

.prettierignore
=> chore: ignore Pipfile.lock from prettier

.github/workflows/publish-docs.yml, Makefile, bin/build-decoder.sh, deps/cache-decoder/package.json, mkdocs.yml
Make it possible to use cache decoder files during deploy
=> fix(cache-decoder): Fix cache decoder deploy

.gitpod.yml
=> chore(gitpod): install pipenv

.gitpod.yml
- install python version from local file
- fixes #233
=> chore(gitpod): install local pythong version

.gitignore, .vscode/settings.json
This eliminates errors when changing the mkdocs config yaml
=> chore: add vscode settings fro custom mkdocs yaml tags

Pipfile, Pipfile.lock, bin/get-docs.sh, mkdocs.yml
- add new nav, allows us to define the nav menu inside renovate docs instead of needing to update here
- https://github.com/renovatebot/renovate/pull/19188
=> docs: new nav generation

.devcontainer/Dockerfile
=> chore(devcontainer): unpin docker image

cypress/e2e/sample.cy.ts
- Updated the `prevUrl` check in the cypress test
- Updated `prevUrl` to point to same folder.
- Fixes failing test in https://github.com/renovatebot/renovatebot.github.io/pull/289
=> test: modify `prevUrl` in if-check 

.devcontainer/Dockerfile
=> chore: fix devcontainer commands

bin/get-docs.sh
merge confidence related markdown file should be now internal and shouldn't be remotely fetched.
- https://github.com/renovatebot/renovate/issues/22891#issuecomment-1603884537
=> fix(docs): remove remote fetching of merge-confidence.md

includes/abbreviations.md
- put product name in abbreviations file
Helps with:
- https://github.com/renovatebot/renovate/issues/23333
Show a _hover text_ when the user hovers over the product name.
=> chore: put product name in abbreviations file

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/post-create.sh, .github/workflows/publish-docs.yml, Makefile
This PR takes the improvements from https://github.com/renovatebot/renovate/pull/23378 and https://github.com/renovatebot/renovate/pull/23412 and applies them to this devcontainer, among other improvements which are specific to this project.
Described above.
=> chore: improve devcontainer

includes/abbreviations.md
- Add abbreviations:
- CA
- mTLS
- PEM 
These abbreviations are used in this PR:
- https://github.com/renovatebot/renovate/pull/24155
=> chore: add abbreviations

src/index.md
- Copy/paste updated list item from: https://github.com/renovatebot/renovate/pull/24293
Closes #315
=> docs: more managers now support replacement PRs

.github/workflows/publish-docs.yml, bin/get-docs.sh
renovate uses pnpm instead of yarn
=> fix: use pnpm

.devcontainer/Dockerfile
=> chore: use pnpm

.gitpod/Dockerfile
https://github.com/renovatebot/renovatebot.github.io/pull/244
Try here: https://gitpod.io/#https://github.com/renovatebot/renovatebot.github.io/pull/326
=> Ensure gitpod user has the correct GID

src/release-notes-for-major-versions.md
- Link to `v37` release notes
Follow-up after:
- #327
All other release note sections have a link to the release notes, so `v37` should too.
=> chore: link to Renovate v37 release notes

.prettierrc.json, package.json, pnpm-lock.yaml
switch and enable prettier plugin
=> chore: prettier fixes

.devcontainer/Dockerfile, .github/workflows/publish-docs.yml
- `~/.cache/Cypress` is not cached so  cypress runs fails
- devcontainer fails because of a parcel error
=> ci: fix caching and devcontainer

.github/workflows/publish-docs.yml
- enable global pnpm cache again
=> ci: fix cache again

.github/workflows/publish-docs.yml
=> ci: add name to cache step

src/index.md
=> docs: fix links

mkdocs.yml
`nav` is not required for pages plugin. Validated locally.
- #305
- https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/issues/92#issuecomment-1832033210
=> fix: remove obsolete nav item

.gitpod/Dockerfile
=> chore: unpin gitpod image

.devcontainer/devcontainer.json
=> chore(devcontainer): use init

.devcontainer/devcontainer.json
=> chore(devcontainer): disable start command to fix ci

src/security.txt
- Bump expiry date of the `security.txt` file
This file tells security researchers how to contact Renovate. It's nearing the expiry date, so I'm bumping the date again.
=> chore: bump security.txt expiry date

bin/prepare-vercel.sh
- Fix typo in constant, from `PYTON_VERSION` to `PYTHON_VERSION`
Follow-up after:
- #387
=> chore: fix typo in prepare-vercel script

poetry.lock, pyproject.toml
As suggested by the mkdocs-material maintainer
=> build: drop direct mkdocs dependency

.devcontainer/post-create.sh, .github/workflows/publish-docs.yml, .gitpod.yml
- disable husky on ci
- use pnpm action
- disable corepack download promt
- closes #453
=> chore: simplify ci and container

renovate.json
Currently patch updates for `.python-version` are blocked by approval
=> chore(renovate): separate minor and patch for python

mkdocs.yml
- Warn us about missing/wrong anchors in links with this new line:
```
validation:
anchors: warn
```
Closes #439
=> chore: validate anchors in links, warn if missing/wrong

bin/get-docs.sh
See failing PR's.
Our pnpm versions can be out of sync an then they cause issues.
So use explicit corepack to build renovate docs
- https://github.com/renovatebot/renovatebot.github.io/pull/467
- https://github.com/renovatebot/renovatebot.github.io/pull/468
=> build: use corepack for renovate

mkdocs.yml
- Drop comments about obsolete extra js
Follow up after:
- #485
=> docs: drop comments about obsolete extra js

.github/workflows/devcontainer.yml
Will cause less failures because of secondary rate limit
- https://github.com/renovatebot/renovate/pull/29221
=> ci: skip github issues on devcontainer tests

src/security.txt
- Bump expiry date for `security.txt`
Closes #511.
=> chore: update security.txt

.devcontainer/Dockerfile, .devcontainer/post-create.sh, .gitpod.yml, .gitpod/Dockerfile, bin/get-docs.sh
=> build: use pnpm instead of corepack

.devcontainer/Dockerfile, .devcontainer/post-create.sh, .github/workflows/devcontainer.yml, .github/workflows/publish-docs.yml
ensure proper permissions
- https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_specifying-a-user-for-vs-code
=> chore: fix devcontainer

.devcontainer/Dockerfile
=> chore: drop temporary fix

bin/get-docs.sh
=> chore: drop workaround

.devcontainer/Dockerfile, .gitpod/Dockerfile, package.json
| datasource | package | from   | to     |
| ---------- | ------- | ------ | ------ |
| npm        | pnpm    | 10.6.1 | 10.6.3 |
=> chore(deps): update dependency pnpm to v10.6.3

bin/get-docs.sh
Reverts renovatebot/renovatebot.github.io#645
=> chore: drop workaround 

bin/get-docs.sh
pnpm has issues, so using corepack. docs pnpm version is sometimes out of sync with this repo's pnpm version.
- https://github.com/pnpm/pnpm/issues/9715
- https://github.com/renovatebot/renovatebot.github.io/pull/705#issuecomment-3375550627
=> chore: use corepack to build docs
