renovatebot/renovatebot.github.io

mkdocs.yml

I'm not sure what's the best position in the sidebar for the automerge config docs.
Automerging is something that a lot of people want, so we could put it front and center in the `Getting Started:` sidebar.
Or we could say that automerging is something more advanced, and should go in `Deep Dives:`.
Fixes #30

Add automerge configuration to sidebar

---

mkdocs.yml

Currently we publish the doc page, but no link in sidebar to find it

docs: add self-hosting link to sidebar

---

README.md

I think the badge looks better on top, instead of right after a `h1` heading. 😄

chore: move badge to top of README

---

renovate.json

- Only allow main Docusaurus v2 releases
I'm using this in my own Docusaurus v2 repo to filter out the `canary` releases that Docusaurus releases on a regular basis.
Those `canary` releases are not meant for general use, so we should probably filter them out to reduce noise.
Source of regex: https://github.com/RoostingGeese/git-gosling/blob/main/renovate.json
---
Edit: @viceice You could also copy/paste this into your Docusaurus migration branch later, just wanted to let you know about this. 😄

chore: only allow main Docusaurus v2 releases

---

.github/workflows/publish-docs.yml
README.md

- Rename `docs.yml` -> `publish-docs.yml`
- Rename name within action from `docs` -> `publish-docs`
- Update badge in README to use the new name
The end goal of this GitHub Action is to publish the docs.
So I think it makes more sense to name the action: `publish-docs.yml` and use `publish-docs` as the action name.
I've also updated the badge to use the new name.

ci: rename docs -> publish-docs and update badge

---

README.md

- Copy/paste security section from Renovate bot main README
We have a SECURITY.md file, so that covers the Security tab on this repo, but we don't yet mention the security email in the README.md
This ensures we have the maximum chance to redirect security concerns to email.

chore: create security section in README

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/config_help_for_renovate_bot.md
.github/ISSUE_TEMPLATE/feature_request.md

- Create issue templates for:
- Bug reports
- Feature requests
- Redirect config help for Renovate bot to discussions on main Renovate bot repo
- Prevent users from opening empty issues by setting `blank_issues_enabled` to `false` in the `.github/ISSUE_TEMPLATE/config.yml` file
- Use the new `contact_links` option in the `config.yml` file to redirect users with config questions.
Closes #43.
I found a really nice feature in the GitHub docs, turns out you can just flat-out ignore empty issue templates with a `config.yml` file. This prevents spammers from opening empty issues.
Quote from [GitHub docs, configuring the template chooser](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser):
> You can …

chore: create issue templates

---

mkdocs.yml

- Move FAQ so that is has its own entry in the sidebar
The current location of the FAQ makes it unlikely that new Renovate users actually find it.
EDIT: we have decided to put the FAQ in the sidebar by itself.

docs: move FAQ to stand-alone entry on sidebar

---

.github/workflows/publish-docs.yml

- Replace `node-version: 12.x` with `node-version: 14.x`
@viceice said we only support the latest LTS, so we should probably update the action.

ci: use Node 14

---

.npmrc
.yarnrc

- Tell Yarn to use pinned versions (exact versions) when installing (dev) dependencies
We have setup our Renovate bot to use pinned dependencies, but when you use Yarn locally, you can still accidentally install packages using a range.
This PR makes it so that Yarn will always install using a exact version.

chore: pin versions when installing deps locally

---

mkdocs.yml

- Add Renovate Scheduling under Key Concepts category 
I hope this is correct to add the new page "renovate scheduling" from https://github.com/renovatebot/renovate/pull/11278 to the sidebar.
Please check my work! 😉

docs: add Renovate Scheduling under Key Concepts category

---

mkdocs.yml

- File was renamed upstream from `docs/usage/automerge-configuration.md` to `docs/usage/key-concepts/automerge.md`
- Move file to new key-concepts category in the sidebar
Upstream PR to track:
- https://github.com/renovatebot/renovate/pull/11490
Only merge this PR once you see the new section `automerge` in https://github.com/renovatebot/renovatebot.github.io/tree/main/key-concepts

docs: rename file, move automerge to key-concepts

---

renovate.json

Reverts renovatebot/renovatebot.github.io#51

Revert "chore: only allow main Docusaurus v2 releases"

---

.github/contributing.md
.github/local-development.md

- Create local development docs based off [renovatebot/renovate/docs/development/local-development.md](https://github.com/renovatebot/renovate/blob/master/docs/development/local-development.md)
- Adjust docs where needed so that they have the correct instructions
We have nothing that accurately describes the current steps to re-create the documentation website locally.
I know we're going to migrate to Docusaurus v2 sometime, but we should have at least a template that we can fill in properly later.

docs: create local development docs

---

mkdocs.yml

- Add new page "Troubleshooting Renovate` to the sidebar
We can merge this once we see that the `troubleshooting` folder exists in https://github.com/renovatebot/renovatebot.github.io/tree/main
Upstream PR that adds the documentation page: https://github.com/renovatebot/renovate/pull/11897
Upstream PR that moves the file to a better location: https://github.com/renovatebot/renovate/pull/11937

docs: add troubleshooting file to sidebar

---

mkdocs.yml

Add the following preset pages to the sidebar:
- 'Workaround Presets'
- 'Compatibility Presets'
- 'npm Presets'
- 'Regex Manager Presets'
Now all preset pages have a entry in the sidebar. 😉

docs: add missing presets to sidebar

---

.github/workflows/lock.yml

- Update `dessant/lock-threads` to `v3`
- Migrate input names to newer terms
- Specify permissions
- Limit concurrency
Basically a copy/paste of the file we have over on the main renovate repository: https://github.com/renovatebot/renovate/blob/main/.github/workflows/lock.yml with one small adjustment to keep `if: github.repository == 'renovatebot/renovatebot.github.io'` from the file we have now.

chore(deps): update dessant/lock-threads action to v3

---

mkdocs.yml

- Add upstream new page covering Known Limitations to the sidebar
This upstream PR should be merged first: https://github.com/renovatebot/renovate/pull/11946
We can merge this PR once we see the new folder Known Limitations here: https://github.com/renovatebot/renovatebot.github.io/tree/main

docs: add Known Limitations to sidebar

---

mkdocs.yml

- Use `site_description` to add a meta tag to head in HTML [^mkdocs-site-description]
- Use `strict` mode: halt processing when a warning is raised [^mkdocs-strict]
I noticed we don't have any site description in our Renovate docs HTML head section right now, so we might want to add a generic description here.
While browsing the MkDocs documentation I saw that they have a `strict` mode, it will complain if you mess up the `mkdocs.yml` config file when doing local work. I think having the program complain and abort is better than silently eating any errors, but maybe you want the publishing of the docs to continue whatever happens.
Not closing any issue with this PR.
[^mkdocs-site-description]: https://www.mkdocs.org/user-guide/configuration/#site_description
[^mkdocs-strict]: …

chore: improve MkDocs configuration

---

mkdocs.yml

- Enable syntax highlighting
We can use syntax highlighting for any Markdown code blocks that have the language mentioned after the three backticks, like this:
```json
{
"extends": ["config:base", ":disableDependencyDashboard"]
}
```
The documentation for this option can be found here: [Material for MkDocs, Python Markdown Extensions, Highlight](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight).
I think it looks better this way! Let me know what you think. 😉
Not closing any existing issue with this.

chore: enable syntax highlighting

---

mkdocs.yml

Reverts renovatebot/renovatebot.github.io#97
I think we should revert this change and figure out what's causing the bad behavior as described in bug report #99. Once we fix bug #99 we can re-enable syntax highlighting again.
It's a shame this breaks the display here, because I do like it when it works properly. 😞

Revert "chore: enable syntax highlighting (#97)"

---

src/index.md

- Update outside contributors number
Steps to reproduce:
1. Run `git shortlog --numbered --summary > summary-contributors.md` on the latest `main` branch of the `renovatebot/renovate` repository.
1. Open the generated file in the IDE,  scroll down to bottom of file to see the linenumber.
1. Right now the linenumber is `516`. 🥳 
Easier method: go to the https://github.com/renovatebot/renovate homepage and look at the sidebar:

docs(index): update outside contributors number

---

renovate.json

- Improve our Renovate configuration so that we get `minor` python package update PRs automatically
- Remove the requirement to request minor python package updates from the Dependency Dashboard
Closes #121.

chore: get PRs for minor python, don't automerge

---

mkdocs.yml

- Integrate the table of contents into the sidebar on the left
Quote from the docs: [^docs]
> When navigation integration for the table of contents is enabled, it is always rendered as part of the navigation sidebar on the left.
**Pros:**
- It's more intuitive to have a summary of the content in the sidebar on the left
- All content can now be searched in one place, instead of spread out over two sidebars.
- The new layout has more space for the actual content, right now the content is "squished" between two sidebars
**Cons:**
- It's different than what we had before
- It can be a bit of a scroll to reach the end of the sidebar on the left, for example if you're on the Repository Config options page
**Same:**
- There is a problem with longer text not being displayed fully in the sidebar, …

chore: integrate table of contents

---

mkdocs.yml

- Enable instant loading
This is the killer feature of Material for MkDocs and we're not using it, quote from the docs (I've **bolded** the relevant part):
> Material for MkDocs provides a multitude of options to configure the behavior of navigational elements, including tabs and sections, **and its flag-ship feature: instant loading.**
I'll let the docs explain: [^docs]
> When instant loading is enabled, clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page.
>
> The resulting page is parsed and injected and all event handlers and components are rebound automatically, i.e., Material for MkDocs now behaves like a Single Page Application.
> Now, the search index survives navigation, which is especially useful for large documentation sites. …

chore: enable instant loading

---

mkdocs.yml

- Document `mkdocs.yml` config settings
- Put the configuration options in a more logical order
- Add `admonition` markdown extension
The big idea is that you can go through the config options in roughly the same order as you see the items on the published page.
I've kept the navbar/sidebar at the bottom like it is right now.
**EDIT:** I've also added the config option that I need to allow admonition blocks to work.
Closes #129
Closes #132

chore: document mkdocs.yml config settings, add admonition feature

---

mkdocs.yml

- Add permalink behind headings
When you hover/tab behind the heading name, you'll see a "paragraph" icon that contains a permanent link to that heading.

chore: add permalink behind headings

---

mkdocs.yml
src/about-us.md
src/index.md

- Rewrite index page to be simpler and quicker to read
- Create about us page
I think this is easier and quicker to read and understand.
Some text should go in a "About Us" page, so I've split the text over two pages.

docs: rewrite index page, create about us page

---

.github/contributing.md
README.md
SECURITY.md

- Rewrite security sections
Follow-up PR after https://github.com/renovatebot/renovate/pull/14773
Copy and paste of the security section from our main Renovate readme. 
Now our security sections are the same in the main Renovate repository and our docs publishing repository.

docs: rewrite security sections

---

src/security.txt

- Create `security.txt` in `src` directory
Fixes #152. I'm following the specs from https://securitytxt.org/.
> **Where should I put the security.txt file?**
> 
> For websites, the security.txt file should be placed under the `/.well-known/` path. It can also be placed in the root directory (`/security.txt`) of a website, especially if the `/.well-known/` directory cannot be used for technical reasons, or simply as a fallback. The file can be placed in both locations of a website at the same time.
I cannot get `.well-known/security.txt` to work. So I'm falling back to `src/security.txt`. 🙈 
The content of the `src/` directory gets copied by this script:
https://github.com/renovatebot/renovatebot.github.io/blob/2bccdd6770bc55b1325c4ee3985a7995de489d80/bin/get-docs.sh#L1-L26

docs: publish security.txt

---

mkdocs.yml

- Swaps the icons for the light and dark mode
**Currently:**
1. Start on Light mode, click on Sun icon to go to Dark mode
2. From Dark mode, click on Moon icon to go to light mode
3. Hover text doesn't match icon
**In this PR:**
1. Start on Light mode, click on Moon to go to dark mode
2. From Dark mode, click on Sun to go to light mode
3. Hover text matches icon

chore: change light/dark mode toggle icon order

---

mkdocs.yml

- Add key concepts page for presets to the sidebar/nav
I forgot to add the new key concepts presets page to our sidebar after merging PR https://github.com/renovatebot/renovate/pull/15396. So I'm fixing the sidebar with this PR now. 😄

docs: add presets key concepts page to sidebar

---

src/about-us.md

- Replace `Whitesource` with `Mend` in about us page
Let's fix this, until we merge https://github.com/renovatebot/renovate/pull/15661. 😉

docs: use new brand name in about us page

---

mkdocs.yml

- Enable collapsible admonition blocks by using the `pymdownx.details` [^docs] extension
We're using `??? note` admonitions, which are "collapsible", in this PR: https://github.com/renovatebot/renovate/pull/15791. This will only work with the changes in this PR.
[^docs]: [Material for MkDocs documentation, Details](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=details#details)

chore: enable collapsible admonition blocks

---

src/index.md

This PR updates the link to the Dockerimage, it seems that, when not logged in, the current link just points to a login page.
- https://hub.docker.com/repository/docker/renovate/renovate:
- The new link shows it correctly:

fix: Update link to docker image

---

.gitignore
mkdocs-hooks/custom-edit-url.py
mkdocs.yml
requirements.in
requirements.txt
src/index.md

This PR iterates on #139 and adds a hook, which allows to overwrite the `edit_url` via YAML font matter 
This PR is similiar to #139 and makes it obsolete if accepted. //cc @HonkingGoose

fix: add custom `edit_url` mkdocs hook

---

.prettierignore
includes/abbreviations.md
mkdocs.yml

- Create list of common abbreviations
- Change `mkdocs.yml` config file so the tooltip feature can work [^tooltips]
- Edit `.prettierignore` file to prevent Prettier from messing up the formatting of the abbrevations list
Replaces PR #194, that I messed up when merging `main` into my fork's branch.
[^tooltips]: https://squidfunk.github.io/mkdocs-material/reference/tooltips/

chore: show tooltip when hovering over abbreviation

---

.prettierignore
mkdocs.yml

- Add configuration for Material for MkDocs to get emojis working [^material-docs]
- Add `mkdocs.yml` to `.prettierignore` file to prevent messed up comments
The swissquote article has `:smile` 😄 emoji at the end of the article. Right now this emoji doesn't render properly.
This PR changes things so that the `:smile:` shortcode is recognized, and rendered as 😄.
Closes #210.
I turned off Prettier for the `mkdocs.yml` file, as it moves my comments around.
```yaml
- attr_list
- pymdownx.emoji:
emoji_index: !!python/name:materialx.emoji.twemoji
emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.details
```
```yaml
- attr_list
- pymdownx.emoji:
emoji_index: !!python/name:materialx.emoji.twemoji
emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.details
``` …

chore: get emojis working

---

src/index.md

- Replace text that talks about the tutorial with a secondary call to action button

docs(index): add button for tutorial

---

.prettierignore
mkdocs.yml
overrides/main.html

- Add announcement bar with a link to the latest Renovate `major` version
Closes #131.

chore: add announcement bar

---

overrides/main.html

- Rewrite announcement bar text to explain:
- That _we_ made a new user stories section, about how individuals and companies use Renovate
- That the _first_ article is about how Swissquote uses Renovate
Clearing up some confusion from readers about the new section. I hope the new text also shows that it's about _other_ companies that use Renovate bot, not that Swissquote suddenly _owns_ Renovate bot.

chore: change announcement bar text

---

includes/abbreviations.md

- Add the JDK abbreviation to the list
We use the JDK abbreviation in the [Renovate docs for the Adoptium Java Datasource](https://docs.renovatebot.com/modules/datasource/#adoptium-java-datasource).
Found this missing abbreviation while working on:
- https://github.com/renovatebot/renovate/pull/17411

chore(abbreviations): add JDK to the list

---

src/index.md

- Enable lazy-loading for the images [^docs] on the homepage
Making sure all our images are lazily-loaded.
[^docs]: https://squidfunk.github.io/mkdocs-material/reference/images/#image-lazy-loading

docs: enable lazy-loading for homepage images

---

mkdocs.yml

- Enable the anchor following feature [^anchor-following-docs]
The navigation sidebar now scrolls when you scroll through the content. Now you can always see the anchor link in the sidebar.
This feature will be handy to help users navigate some large pages of our docs, most notably the _Configuration Options_ page. 😉 
1. Open my branch in Gitpod, or your workstation
2. Run `make && make serve`
3. Go to the development preview browser window
4. In the navigation sidebar click on _Configuration_ -> _Repository_ to open the Configuration Options docs
5. Scroll through the page, check the sidebar moves with the page content
[^anchor-following-docs]: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following

chore: enable anchor following

---

mkdocs.yml

- Disable the announcement bar by commenting out the "link" to the `overrides/main.html` file that has the announcement bar content
Commenting out things in the `overrides/main.html` file doesn't get rid of the announcement bar completely (you still see a "flash" of the old content when you refresh or land on the page.
So I'm doing a bit of hack-job here, and just comment out the "link" to the `overrides/main.html` file. This way we keep the code for the announcement bar.
I could also `git revert` the two commits that introduced the announcement bar, and the change to the announcement bar text. But that means having to `git revert` the first `git revert` yet again, after we figure out how to use the announcement bar later. 😄

chore: disable announcement bar

---

package.json

- Enable Prettier's `--cache` option [^prettier-docs]
This speeds up the `yarn prettier` and `yarn prettier-fix` commands when you run them the _second_ time. But the _first_ run of Prettier is slower, because it needs to build the cache.
I'll let you guys decide if the slowdown of the first run (like in GitHub Actions), is worth the speed-up on a second run.
It would be nice if we could get the Prettier cache in our GitHub Actions, so the actions often have a nearly up-to-date cache.
[^prettier-docs]: https://prettier.io/docs/en/cli.html#--cache

ci: enable Prettier cache

---

Pipfile
Pipfile.lock
mkdocs.yml

- Use MkDocs `1.4.0` [^changelog] native `hooks:` feature [^hooks]
- Run `pipenv uninstall mkdocs-simple-hooks` to drop the dependency
Closes #229.
1. Open my branch in Gitpod, or locally
1. Run `make && make serve`
1. Go to the Merge Confidence page in the preview
1. Click on the pencil icon (edit button)
1. Confirm you're taken to the correct source file on the correct repository
[^changelog]: https://github.com/mkdocs/mkdocs/releases/tag/1.4.0
[^hooks]: https://www.mkdocs.org/user-guide/configuration/#hooks

build: use mkdocs-native hooks

---

src/release-notes-for-major-versions.md

- Add `edit_url` yaml override
The edit button (pencil icon) doesn't lead users to the correct location. We can override the default `edit_url` at the top of the page.
https://github.com/renovatebot/renovatebot.github.io/blob/650fb9126973f87298d3e2cd1288756a6697f800/mkdocs-hooks/custom-edit-url.py#L1-L6

chore: add edit_url override to release notes page

---

mkdocs.yml

- Pick better colors to improve contrast:
- Use a darker `indigo` for the light mode
- Use a calmer `teal` color for the dark mode
Material for MkDocs allows custom colors beyond just the "standard color" words, but to do that I would need to override the theme with custom CSS. I don't want to mess too much with the Material for MkDocs theme as that's prone to break. [^customization]
So instead I'm picking better colors from the existing "color words". With the new colors most elements get a WCAG AA contrast rating. [^rating] But some elements still lack good contrast. You can use the accessibility tools in Firefox or Chrome to check the contrast of each element on screen.
I think this is about the best that I can get it, without messing with the custom CSS. 🙈 
[^customization]: …

chore: improve theme color contrast

---

src/security.txt

- Bump expiry date to 31th of December 2023
Optional changes:
- Add `Canonical` field that links to our Renovate docs domain
- Add link to our security policy (I'm linking to the one on the Renovate docs repository!)
The `security.txt` expires in December of this year. Let's bump the dates now, so we don't forget later. 😄 
I think we should add the Canonical and Policy fields.
Read the docs:
- https://securitytxt.org/

chore: update security.txt

---

mkdocs.yml

- Re-enable copy-to-clipboard button
- Re-enable edit source button
- Re-enable next/previous buttons in the footer
- Enable view source button (This one is new, turns out it works now, but it was broken in the beta)
- Use pencil icon for edit page button (like we have now)
- Use eye icon for view source of the page button
Here are my changes for the Renovate update branch for Material for MkDocs 9. I'm targeting Renovate's branch with this PR, so we can review and discuss the changes in the PR before we merge things. 😉

Re-enable old features, get new features

---

mkdocs.yml

- Copy/paste @TWiStErRob's regex
I first started by copy/pasting the example regex from the Material for MkDocs manual, and then @TWiStErRob had a better regex for us to try.
Read the [Material for MkDocs about `separator`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search-plugin).
Helps with issue #264.

chore: setup tokenization

---

mkdocs.yml

fix: better tokenization

---

mkdocs-hooks/custom-edit-url.py

- Capitalize abbreviation YAML
- End sentence with full stop
Drive-by PR. 😄

chore: capitalize abbreviation, add fullstop

---

mkdocs.yml
overrides/main.html

- Enable the announcement bar in config again
- Write announcement bar text for brownout
Related discussion: 
- https://github.com/renovatebot/renovate/discussions/20613

chore: enable announcement bar, explain brownout

---

overrides/main.html
src/release-notes-for-major-versions.md

- Add release notes for Renovate `v35`
- Add `v35` to announcement bar
- Drop deprecation notice
- Add maintainer commentary by `@rarkins`
Let the docs readers know that we've released Renovate `v35`.

chore: add release notes for v35, edit announcement bar

---

overrides/main.html

- Add `ghcr.io` announcement
We're now also publishing images via `ghcr.io`. We should tell our users.

chore: add `ghcr.io` announcement

---

includes/abbreviations.md

- Add `VM` abbreviation to glossary
Add missing abbreviation to the glossary. This means that when you hover over the `VM` abbrevation, you see a small pop-up with the full term "Virtual Machine".

chore: add vm abbreviation to glossary

---

includes/abbreviations.md

- Add `AUR` abbreviation to glossary
Only merge this _after_ this PR:
- https://github.com/renovatebot/renovate/pull/21413

chore: add AUR abbreviation to glossary

---

mkdocs.yml
overrides/main.html

- Disable the announcement bar in the MkDocs config file by commenting out a line
- Remove the text about us publishing container images on GHCR
We've shown the `v35` and the GHCR announcements for over a month. Most readers will have seen the new stuff by now. 😄

chore: disable announcement bar, remove GHCR text

---

mkdocs.yml
overrides/main.html
src/release-notes-for-major-versions.md

- Update our Release notes for major versions document
- Enable the announcement bar, and point to `v36` release notes in it
We released Renovate `v36`. 🥳 So we should update our own release notes and commentary. 😉

chore: release notes for v36

---

src/index.md

- Add Forgejo to list of supported platforms
- Use `the Mend Renovate app` to refer to the GitHub-hosted app
- Split the Mend Renovate app from the three list items, into its own sentence
- Update call to action button text
Related issue:
- https://github.com/renovatebot/renovate/issues/23333
Preview image for the improved index page:

docs: update index page

---

mkdocs.yml

- Enable new Material for MkDocs feature: navigation pruning [^1]
> When pruning is enabled, only the visible navigation items are included in the rendered HTML, __reducing the size of the built site by 33% or more__. Add the following lines to `mkdocs.yml`:
> 
> ``` yaml
> theme:
>   features:
>     - navigation.prune
> ```
> 
> This feature flag is not compatible with `navigation.expand`, as navigation expansion requires the complete navigation structure.
> 
> This feature flag is especially useful for documentation sites with 100+ or even 1,000+ of pages, as the navigation makes up a significant fraction of the HTML.
> Navigation pruning will replace all expandable sections with links to the first page in that section (or the section index page).
[^1]: …

chore: enable navigation pruning

---

mkdocs.yml

- Removes `toc.integrate` so we have a left and right sidebar again
Reverts this PR, with some extra changes to remove the comments:
- #128

chore: have two sidebars again

---

README.md

- Update `publish-docs` action status badge in our readme
The badge we have now shows `no status`.
The [`publish-docs` status check](https://github.com/renovatebot/renovatebot.github.io/actions/workflows/publish-docs.yml) also runs on other branches, but we probably only want to show the results of the `main` branch runs. So I'm limiting the badge to only show `main` branch results.

chore: update publish-docs badge in readme

---

mkdocs.yml
overrides/main.html
src/release-notes-for-major-versions.md

- Copy/paste breaking changes from [Renovate's `37.0.0` changelog](https://github.com/renovatebot/renovate/releases/tag/37.0.0)
- Draft developer commentary
- Update announcement bar text to `v37` and enable it again
The hosted app is now using `v37`, so we should highlight the changelogs again in our docs.

chore: release notes for Renovate v37

---

Pipfile
Pipfile.lock
mkdocs.yml

- Drop the `mkdocs-material-extensions` dependency because it's built-in to Material for MkDocs `9.4.0` [^1]
- Update Material for MkDocs config so it uses the built-in emoji stuff
Supersedes PR #332.
[^1]: [Material for MkDocs `9.4.0` changelog, `emoji` highlighted](https://squidfunk.github.io/mkdocs-material/changelog/?h=emoji#9.4.0)

chore: drop mkdocs-material-extensions dependency

---

src/assets/css/style.css

- Underline links for accessibility
We should underline links in the body text, because:
- Relying on color alone is bad for colorblind users, or those who prefer grayscale
- It clearly shows which part of the text is a link
- Underlining links is the default browser styling anyways
- GitHub defaults to underlining links [GitHub Blog, New Default: Underlined Links for Improved Accessibility](https://github.blog/changelog/2023-10-18-new-default-underlined-links-for-improved-accessibility/)
Material for MkDocs lacks a toggle for link underlining, so I'm overriding the default CSS.
- https://github.com/squidfunk/mkdocs-material/discussions/6238

chore: underline links

---

mkdocs.yml

- Enable Material for MkDocs's built-in `Mermaid.js` diagram support [^1]
- Removing the "search highlights" from the links to the Material to MkDocs manual.
The new config allows Material for MkDocs to show the `Mermaid.js` diagrams properly.
The [Renovate docs for the Rubygem datasource](https://docs.renovatebot.com/modules/datasource/rubygems/) uses a `Mermaid.js` diagram.
[^1]: [Material for MkDocs, diagrams](https://squidfunk.github.io/mkdocs-material/reference/diagrams/)

chore: enable Mermaid.js diagrams

---

mkdocs.yml

- Configure automatic light / dark mode [^1]
- Watch the `includes` directory, so the preview updates when you edit the `abbreviations.md` file
Material for MkDocs reached another funding goal [^3], so we get access to new features. :partying_face: 
There's a privacy plugin [^2], but that only works with fully qualified URLs, and we autogenerate a lot of stuff with scripts. So I don't know if the Privacy Plugin would work properly.
[^1]: [Material for MkDocs, automatic light / dark mode](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode)
[^2]: [Material for MkDocs, privacy plugin](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin)
[^3]: [Material for MkDocs, $14,000 Goat's Horn …

chore: improve Material for MkDocs config

---

bin/prepare-vercel.sh

Vercel now uses amazon linux 2023 which comes with python 3.9 and openssl v3 🎉 
So i simplified the install steps.
They also support python 3.11, so we can probably rais our requirements to that version too.
- https://renovatebot-docs-30k7k0ode-viceice.vercel.app/
- https://renovatebot-docs-git-chore-amz-lnx-2023-viceice.vercel.app/

chore(vercel): update for amazon linux 2023

---

.gitignore
mkdocs.yml
src/assets/js/fx.js

Those are no longer needed:
- page title: mkdocs already adds `- Renovate docs` suffix
- logo link: i checked that all it works on all pages already without changing.
- https://github.com/renovatebot/renovate/issues/23772

docs: drop obsolete extra js

---

src/assets/css/style.css

- use rem unit (logo is now 36px instead of 35, but better scalable)
- remove padding from outer anchor for better alignment (was a little shifted to top
- remove right margin to align with drawer on small page sizes.
- https://github.com/renovatebot/renovate/issues/23772

docs: optimize logo style

---

.github/workflows/lock.yml

Automatic token has rate limit, so let's try a diffent schedule than the main repo.
- https://github.com/dessant/lock-threads/issues/48#issuecomment-2069165802

ci: use different lock schedule

---

mkdocs.yml
overrides/main.html

- Rewrite announcement bar text
- Update to mention `v38`
- Uncomment the `custom_dir: overrides` part in the `mkdocs.yml` config file, to enable the announcement bar
We released `v38` of Renovate OSS.
I think Mend is rolling out `v38` to hosted app users now too. Or at least the roll out was planned for Sunday 4th of August.
Related things:
- https://github.com/renovatebot/renovate/discussions/30417
- https://github.com/renovatebot/renovate/pull/30384
In any case, the docs should highlight the release notes. 😄

chore: enable announcement bar for v38

---

bin/get-docs.sh

Reverts renovatebot/renovatebot.github.io#642
otherwise ci fails, see #644

fix: Revert "chore: drop workaround"
